### ISSUE TITLE
App Home Page

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#131]
- ### in top where business name is showing --> add edit button to edit business name and create new or choose another business
- 
![WhatsApp Image 2023-05-25 at 10 44 12](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/c14cd28f-83bc-43c0-81d4-d7b70dc26788)
![WhatsApp Image 2023-05-25 at 10 44 30](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/06a5cfd5-1d6e-424d-967c-5a66eee932d1)

**Comment by raja9380** [comment]
need to discuss with sir
