### ISSUE TITLE
App Hisab Page for customer and supplier

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#132]
### Increase border radius for Add new customer button and add new supplier button. 
![WhatsApp Image 2023-05-25 at 11 42 52](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/6c53fb03-88be-4c00-96a4-1fe55c357158)
![1](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/66746e4d-635e-4c7a-8c5d-0981f835d1e4)

**Comment by raja9380** [comment]
need to discuss with sir
