### ISSUE TITLE
App Hisab page add New Customer and  add new supplier

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#133]
- ### in add new customer page and add new supplier page when we put customer name or supplier name without mobile number it not working
- ### when we add customer or Add supplier without transaction customer name or supplier name not showing anywhere.
![WhatsApp Image 2023-05-25 at 11 50 02](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/a18501a1-658a-4af7-ad8b-a93b951e2378)

**Comment by raja9380** [comment]
this flow is correct
