### ISSUE TITLE
App Hisab Customer/supplier Transaction Page

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#134]
- ### Add View setting option to edit or delete customer / supplier
![WhatsApp Image 2023-05-25 at 11 17 56](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/d3d4500d-6840-48a9-b7fd-a33bf1e2aef4) 
![WhatsApp Image 2023-05-25 at 11 17 55](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/dd302071-c88c-4ecf-ba81-906025d3ff08)

**Comment by raja9380** [comment]
need to discuss with sir
