### ISSUE TITLE
App Hisab Page For Specific Customer/supplier

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#136]
- ### all transaction should showing by date wise and table format like Entries (date, time, and balance), you gave, you got
- ### replace text "total amount you will give" to "you will get"(when you gave money)
- ### replace text "total amount you have received " to "you will give"(when someone gave money to you)
- ### when given and getting money equal showing settled up 0
- ### Add set collection reminder option after "You will get "heading
- ### Add payment option where WhatsApp, message, report showing
![WhatsApp Image 2023-05-24 at 13 02 01](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/b27c4955-1946-44db-9ca9-7ce50dc812a1)
![WhatsApp Image 2023-05-24 at 13 02 02](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/554896c9-3697-482d-b24b-25c185c30742)
![WhatsApp Image 2023-05-24 at 14 48 27](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/55c124e8-d083-403e-ae7b-4d9b2824e2c8)
![WhatsApp Image 2023-05-25 at 11 07 45](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/70d87e14-7fa9-4e1e-8210-68ee8f19ad29)

**Comment by raja9380** [comment]
need to discuss with sir
