### ISSUE TITLE
App Hisab Page Customer

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#137]
- ### change text and color(set color green and red) to you will give and you will get
- ### Add filter option below search bar like(All, due today, upcoming, no due date)
- ### Add filter and pdf option beside search bar 
![WhatsApp Image 2023-05-24 at 14 35 50](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/a5d21829-de23-49c3-a59f-dc277b599ad5)
![WhatsApp Image 2023-05-24 at 14 35 50](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/228c3cf8-7e7f-440f-8b00-462cd90e8e9e)

**Comment by raja9380** [comment]
need to discuss with sir
