### ISSUE TITLE
App Hisab specific customer/supplier  transaction report

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#147]
- ### beside the date show time and below the date show balance amount
- ### below the search bar add net balance with amount 
- ### change download pdf and share button 
- ### change table heading give, got to you gave, you got
- ### search bar not working when we write something it not showing
![WhatsApp Image 2023-05-25 at 13 56 27](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/8fa12991-04b1-46f0-a972-a7fc3b60ff6a)
![2](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/546ca300-6806-4083-b3bc-2d83527c5b4e)

**Comment by raja9380** [comment]
need to discuss with sir
