### ISSUE TITLE
App Hisab Supplier Report Page

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#150]
- ### for all supplier amount showing 0
- ### date filter not working

![WhatsApp Image 2023-05-25 at 15 24 01](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/1d49d63b-65f2-4e35-b0b7-5f3bfeeb91d0)

**Comment by raja9380** [comment]
api issue asign babu da
