### ISSUE TITLE
In the home page for customer report to give showing in green and in the customer report page you got showing in green

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#162]
![WhatsApp Image 2023-06-01 at 11 33 08](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/096b45a9-a6f6-48d9-8aba-a49ca48a79d4)
![WhatsApp Image 2023-06-01 at 11 33 07](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/00079ab0-0d30-4638-a1c3-676b3168ebef)

**Comment by raja9380** [comment]
this flow is correct
