### ISSUE TITLE
for customer and supplier in report page when we use date filter and then click download pdf button it showing error and share button not working

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#167]
![WhatsApp Image 2023-06-01 at 13 36 57](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/3e65f83b-e79c-46e0-8b0f-c8244126f31e)
![WhatsApp Image 2023-06-01 at 13 36 58](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/08502082-e69d-487f-a8be-2e2f7dd7af73)

**Comment by raja9380** [comment]
api issue asign babu da
