### ISSUE TITLE
In submit kyc details page when we want upload pan and aadhaar details it not working properly all time

### ISSUE THREAD

**Issue by Megha-Sadhukhan** [AlsoltechSol/onecpeapi#172]
![WhatsApp Image 2023-06-01 at 16 09 33](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/1888bff5-14f6-4654-bca5-479252a72816)
![2](https://github.com/AlsoltechSol/onecpeapi/assets/132542340/dd6c1151-3127-4eef-9882-03fbb73d526d)

**Comment by raja9380** [comment]
api issue asign babu da
